name: nicholsz-asklepian
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - minimap2
    - gofasta=0.0.5
    - pip
    - pip:
        - azure-identity
        - azure-storage-blob
        - git+https://github.com/samstudio8/ocarina.git@bb6047ab0253893e4b918e41474c935fa7ec5aa5
